<?php

/**
 * @file
 * Contains update_destinations.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_help().
 */
function update_destinations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the update_destinations module.
    case 'help.page.update_destinations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Updates the sunset quality information each active Destination') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function update_destinations_cron() {
  $queue = Drupal::service('queue');
  $storage = Drupal::getContainer()->get('entity_type.manager')->getStorage('node');

  $now = new DrupalDateTime('now');
  $destinations = $storage->getQuery()
    ->condition('type', 'destination')
    ->condition('status', 1)
    ->condition('field_sunset_last_updated', $now->format('Y-m-d'), '<')
    ->execute();

  if (empty($destinations)) {
    return;
  }

  foreach ($destinations as $destination) {
    $queue->get('update_destinations_queue_worker')->createItem($destination);
  }
}
