<?php

/**
 * @file
 * Contains sunburst_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sunburst_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sunburst_api module.
    case 'help.page.sunburst_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles API connection for https://sunburst.sunsetwx.com') . '</p>';
      return $output;

    default:
  }
}

function sunburst_api_get_auth() {
  if (!$params = sunburst_api_login()) {
     return FALSE;
  }

  if (!$accessToken =  sunburst_api_session_login($params)) {
     return FALSE;
  }
  return $accessToken;
}

function sunburst_api_login() {
  $options = [
    'auth' => [
      $username,
      $password,
    ],
    'form_params' => [
      'grant_type' => 'password',
      'type' => 'remember_me',
    ],
  ];

  $url = 'https://sunburst.sunsetwx.com/v1/login';
  try {
    $client = \Drupal::httpClient();
    $response = $client->post($url, $options);
    $contents = $response->getBody()->getContents();
    if (empty($contents)) {
      // Add log message.
      return FALSE;
    }

    $contents = json_decode($contents);
    if (empty($contents->session)) {
      return FALSE;
    }
    $params = [
      'client_id' => $contents->session->client_id,
      'client_secret' => $contents->session->client_secret,
    ];
    return $params;

  }
  catch (RequestException $e) {
    kint($e);
  }
}

function sunburst_api_session_login($params) {
//curl -X "POST" "https://sunburst.sunsetwx.com/v1/login/session" -u "a3c5994b-58cf-4767-9b0a-2faf324da4ac:SeMzKSDtnO4WfN1uA1vVVGAYJB7FgMB3" -d "grant_type=client_credentials"Ȁ
  $options = [
    'auth' => [
      $params['client_id'],
      $params['client_secret'],
    ],
    'form_params' => [
      'grant_type' => 'client_credentials',
    ],
  ];

  $url = 'https://sunburst.sunsetwx.com/v1/login/session';
  try {
    $client = \Drupal::httpClient();
    $response = $client->post($url, $options);
    $contents = $response->getBody()->getContents();
    $contents = json_decode($contents);
    return $contents->access_token;
  }
  catch (RequestException $e) {
    kint($e);
  }
}


foreach ($detinations as $destination) {
  $data = sunburst_api_predictions($destination->latlon);
  $values = parse_values($data);
  $values->save();

}

function sunburst_api_predictions($latLong) {
  $accessToken = sunburst_api_get_auth();
//   dpm($accessToken);
//   return;
  $options = [
    'headers' => [
      'Authorization' => 'Bearer ' . $accessToken,
    ],
    'query' => [
      'geo' => $latLong,
    ],
  ];

  $url = 'https://sunburst.sunsetwx.com/v1/quality';
  try {
    $client = \Drupal::httpClient();
    $response = $client->get($url, $options);
    dpm($response->getBody()->getContents());
  }
  catch (RequestException $e) {
    kint($e);
  }
}
